name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [main] # Trigger deployment on the main branch
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: sphinx-notes/pages@v3
        with:
          docs-folder: docs/source  # Path to your Sphinx source folder
          publish: false            # Prevents automatic deployment
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ steps.deployment.outputs.artifact }}